version: "2"
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: drf_api
    stdin_open: true
    tty: true

    ports:
      - "8000:8000"